---
kind: pipeline
name: pihole
type: docker

trigger:
  branch:
  - master
  event:
  - push

steps:
- name: Deploy
  image: docker/compose
  commands:
  - cd pihole
  - docker-compose down
#   volumes:
#   - name: dockersock
#     path: /var/run/docker.sock
  environment:
    DOCKER_HOST: "tcp://10.10.200.5:2376"
    WEBPASSWORD:
      from_secret: admin_password
    FORWARDING_IP:
      from_secret: forward_ip
    FORWARDING_DOMAIN: 
      from_secret: forward_domain
    FORWARDING_REVERSE:
      from_secret: forward_reverse
  when:
    event:
    - push

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
