---
kind: pipeline
name: pihole
type: docker

trigger:
  branch:
  - master
  event:
  - push

steps:
- name: Deploy
  image: docker/compose
  commands:
  - cd pihole
  - docker-compose up -d
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  environment:
    WEBPASSWORD:
      from-secret: admin_password
    FORWARDING_IP:
      from-secret: forward_ip
    FORWARDING_DOMAIN: forward_domain
  when:
    event:
    - push

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
