version: '2.4'
services:
  pihole:
    image: pihole/pihole:latest
    ports:
    - "53:53/tcp"
    - "53:53/udp"
    - "67:67/udp"
    - "443:443/tcp"
    - "80:80/tcp"
    volumes:
    - etc:/etc/pihole/
    - dnsmasq:/etc/dnsmasq.d/
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: ${WEBPASSWORD}
      DNS1: '1.1.1.1'
      DNS2: '1.0.0.1'
      CONDITIONAL_FORWARDING: 'True'
      CONDITIONAL_FORWARDING_IP: ${FORWARDING_IP}
      CONDITIONAL_FORWARDING_DOMAIN: ${FORWARDING_DOMAIN}
      ServerIP: '10.10.200.6'
      VIRTUAL_HOST: 'pihole'
    dns:
    - 127.0.0.1
    - 1.1.1.1
    networks:
      lan_net:
        ipv4_address: '10.10.200.6'
    cap_add:
    - NET_ADMIN
    restart: unless-stopped

networks:
  lan_net:
    external: true

volumes:
  etc:
  dnsmasq:
